name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: trap.sh
    - name: Run tests
      run: bats --formatter tap13 . | tee results.tap
      working-directory: trap.sh
      env:
        BATS_LIB_PATH: ${{ github.workspace }}/lib
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: trap.sh/results.tap
        show: "fail, skip"
      if: always()
