name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      run: |
        git clone --depth 1 --branch v1.10.0 https://github.com/bats-core/bats-core.git /tmp/bats
        sudo /tmp/bats/install.sh /usr/local
        rm -rf /tmp/bats
        sudo mkdir -p /usr/lib/bats/bats-support /usr/lib/bats/bats-assert
        wget -O- 'https://github.com/ztombol/bats-support/archive/refs/tags/v0.3.0.tar.gz' | \
          sudo tar -xz --strip-components=1 -C /usr/lib/bats/bats-support
        wget -O- 'https://github.com/ztombol/bats-assert/archive/refs/tags/v0.3.0.tar.gz' | \
          sudo tar -xz --strip-components=1 -C /usr/lib/bats/bats-assert
    - name: Checkout
      uses: actions/checkout@v3
    - uses: orbit-online/upkg@v0.14.0
    - name: Run tests
      run: bats .
